<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>BadWolfAsciiPlayer</AssemblyName>
    <RootNamespace>BadWolfAsciiPlayer</RootNamespace>
    <Version>1.0.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\tools\ffmpeg.exe" Link="tools\ffmpeg.exe" CopyToOutputDirectory="PreserveNewest" Condition="Exists('..\..\tools\ffmpeg.exe')" />
    <None Include="..\..\tools\ffprobe.exe" Link="tools\ffprobe.exe" CopyToOutputDirectory="PreserveNewest" Condition="Exists('..\..\tools\ffprobe.exe')" />
  </ItemGroup>
  <ItemGroup>
    <None Update="tools\ffmpeg.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tools\ffprobe.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
